// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1746870192);
user_pref("app.update.lastUpdateTime.background-update-timer", 1746870192);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1746870192);
user_pref("app.update.migrated.updateDir3.A88A7A0EE6B236CF", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1746870162);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20240801134912");
user_pref("browser.startup.homepage_override.mstone", "115.14.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastPlatformVersion", "115.14.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.zotero.dataDir", "C:\\Users\\openm\\Zotero");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-general");
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.1.SOURCE");
user_pref("extensions.zoteroWinWordIntegration.lastAttemptedVersion", "7.0.4.SOURCE");
user_pref("extensions.zoteroWinWordIntegration.version", "7.0.4.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20240801134912");
user_pref("gfx-shader-check.device-id", "0x1900");
user_pref("gfx-shader-check.driver-version", "32.0.13031.3015");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("idle.lastDailyNotification", 1746870750);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-msvc-x64");
user_pref("media.gmp-gmpopenh264.hashValue", "06511f1f6c6d44d076b3c593528c26a602348d9c41689dbf5ff716b671c3ca5756b12cb2e5869f836dedce27b1a5cfe79b93c707fd01f8e84b620923bb61b5f1");
user_pref("media.gmp-gmpopenh264.lastDownload", 1746870198);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1746870192);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1746870198);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-widevinecdm.abi", "x86_64-msvc-x64");
user_pref("media.gmp-widevinecdm.hashValue", "59521f8c61236641b3299ab460c58c8f5f26fa67e828de853c2cf372f9614d58b9f541aae325b1600ec4f3a47953caacb8122b0dfce7481acfec81045735947d");
user_pref("media.gmp-widevinecdm.lastDownload", 1746870200);
user_pref("media.gmp-widevinecdm.lastInstallStart", 1746870192);
user_pref("media.gmp-widevinecdm.lastUpdate", 1746870200);
user_pref("media.gmp-widevinecdm.version", "4.10.2710.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1746870750300");
user_pref("sanity-test.device-id", "0x1900");
user_pref("sanity-test.driver-version", "32.0.13031.3015");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20240801134912");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1746870750);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "auth.lower + year");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + year");
user_pref("extensions.zotmoov.dst_dir", "C:\\Users\\openm\\Documents\\konspekt_pack\\07 service\\literature PDF");
